# Обучение базовых моделей

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt, ticker as mticker
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.precision', 4)

In [2]:
from pathlib import Path

path_p1_p2 = Path("..", "data", "processed", "p1_p2_data.csv")
df_p1_p2 = pd.read_csv(path_p1_p2, sep=";")

path_p3 = Path("..", "data", "processed", "p3_data.csv")
df_p3 = pd.read_csv(path_p3, sep=";")

path_altpay5 = Path("..", "data", "processed", "altpay5_data.csv")
df_altpay5 = pd.read_csv(path_altpay5, sep=";")

dfs = [df_p1_p2, df_p3, df_altpay5]

COMMON_DTTM_COLS = [
    'month',
    'first_trx_month_inn',
    'last_active_month_inn',
]

CAT_COLS = [
    'inn_status',
    'top_mcc_group_inn',
    'who_is_this_first_inn',
]

for df in dfs:
    for col in COMMON_DTTM_COLS:
        df[col] = pd.to_datetime(df[col])

    # В каждом df разный набор колонок с датами подключения других продуктов
    first_month_cols = [col for col in df.columns if col.startswith("first_month")]
    for col in first_month_cols:
        df[col] = pd.to_datetime(df[col])

    for col in CAT_COLS:
        df[col] = df[col].astype('category')

## Метрики качества
Основной метрикой качества моделей является Precision@K, поскольку бизнес-задача заключается в эффективном распределении ограниченного ресурса отдела продаж. В рамках задачи capacity отдела составляет 2000 клиентов в месяц, что определяет основное значение K. Дополнительно рассматриваются значения K=500, K=1000 и K=1500 для анализа устойчивости качества ранжирования.

Для оценки относительного качества моделей используется метрика Uplift — отношение Precision@K рассматриваемой модели к Precision@K базовых подходов. В качестве базовых подходов используются:

1. Случайный отбор клиентов
2. Отбор на основе текущих бизнес-правил

Дополнительно для оценки качества ранжирования анализируется зависимость Precision@K от K, что позволяет оценить способность модели выделять наиболее релевантных клиентов в верхней части ранжированного списка.

Также используется метрика Recall@K, отражающая долю всех целевых событий (подключений продукта), попадающих в top-K клиентов, что позволяет оценить полноту охвата моделью потенциально релевантных клиентов.

Для интерпретации результатов в бизнес-терминах рассчитывается ожидаемое количество подключений (Expected Conversions), определяемое как произведение Precision@K на K.

## P1P2

### Случайный отбор

Для случайной модели ранжирования ожидаемое значение Precision@K совпадает с долей положительных объектов в выборке. В связи с этим в качестве baseline используется доля положительного класса, рассчитанная по каждому месяцу.

In [3]:
k_values = [500, 1000, 1500, 2000, 2500]

target_monthly = df_p1_p2.groupby('month').target.sum()
month_sizes = df_p1_p2.groupby('month').size()

precision = (target_monthly / month_sizes).mean()  # macro average

print("Random Selection P1P2")

for k in k_values:
    coverage = (k / month_sizes).mean()
    expected_conversions = precision * k

    print(
        f"K={k:<4} | "
        f"Precision: {precision:.2%} | "
        f"Coverage: {coverage:.2%} | "
        f"Expected Conversions: {expected_conversions:.2f}"
    )

Random Selection P1P2
K=500  | Precision: 0.23% | Coverage: 2.23% | Expected Conversions: 1.15
K=1000 | Precision: 0.23% | Coverage: 4.45% | Expected Conversions: 2.30
K=1500 | Precision: 0.23% | Coverage: 6.68% | Expected Conversions: 3.45
K=2000 | Precision: 0.23% | Coverage: 8.91% | Expected Conversions: 4.59
K=2500 | Precision: 0.23% | Coverage: 11.13% | Expected Conversions: 5.74

### Business-Rule

Критерии релевантности:
- Отсутствие подключённых продуктов `P1`, `P2` (фильтрация уже реализована в `df_p1_p2`)
- Статус `'Active'`, `'Reborn'`
- Группа MCC `!= 'Charity'`

Кандидаты на подключение ранжируется по убыванию `turnover`

In [4]:
def add_rule_flag_p1_p2(df: pd.DataFrame) -> pd.DataFrame:
    active_statuses = ["Active", "Reborn"]
    banned_mcc_groups = ["Charity"]

    df = df.copy()
    
    df["rule_flag"] = (
        df["inn_status"].isin(active_statuses)
        & ~df["top_mcc_group_inn"].isin(banned_mcc_groups)
    ).astype("int8")

    return df


df_p1_p2 = add_rule_flag_p1_p2(df_p1_p2)

Замерим качество.

In [5]:
k_values = [500, 1000, 1500, 2000, 2500]
y_score = 'turnover'

print(f"Business-Rule Selection P1P2, y_score='{y_score}'")

for k in k_values:
    df_k = (
        df_p1_p2.query('rule_flag == 1')
        .sort_values(by=y_score, ascending=False)
        .groupby('month')
        .head(k)
    )

    tp = df_k[df_k['target'] == 1].groupby('month').size()
    fp = df_k[df_k['target'] == 0].groupby('month').size()

    total_positives = (
        df_p1_p2[df_p1_p2['target'] == 1]
        .groupby('month')
        .size()
    )

    tp, fp = tp.align(fp, fill_value=0)
    tp, total_positives = tp.align(total_positives, fill_value=0)

    precision_k = (tp / (tp + fp)).mean()
    recall_k = (tp / total_positives).mean()

    avg_rows = df_k.groupby('month').size().mean()
    expected_conversions = precision_k * avg_rows

    print(
        f"K={k:<4} | "
        f"Precision: {precision_k:.2%} | "
        f"Recall: {recall_k:.2%} | "
        f"Expected Conversions: {expected_conversions:.2f}"
    )

Business-Rule Selection P1P2, y_score='turnover'
K=500  | Precision: 0.56% | Recall: 5.67% | Expected Conversions: 2.80
K=1000 | Precision: 0.55% | Recall: 11.33% | Expected Conversions: 5.53
K=1500 | Precision: 0.52% | Recall: 16.06% | Expected Conversions: 7.80
K=2000 | Precision: 0.53% | Recall: 21.24% | Expected Conversions: 10.60
K=2500 | Precision: 0.53% | Recall: 26.61% | Expected Conversions: 13.33

Попробуем улучшить отбор по бизнес-правилу за счёт изменения столбца ранжирования. Переберём все числовые признаки, кроме `target` и `rule_flag`.

In [6]:
numeric_features = [col for col in df_p1_p2.select_dtypes(include=['number']).columns if col not in ('target', 'rule_flag')]

k_values = [500, 1000, 1500, 2000, 2500]

print(f"Business-Rule Selection P1P2")

for asc in (True, False):
    for feature in numeric_features:
        y_score = feature
        print(f"y_score='{y_score}' {'ASC' if asc else 'DESC'}")
        for k in k_values:
            df_k = (
                df_p1_p2.query('rule_flag == 1')
                .sort_values(by=y_score, ascending=asc)
                .groupby('month')
                .head(k)
            )

            tp = df_k[df_k['target'] == 1].groupby('month').size()
            fp = df_k[df_k['target'] == 0].groupby('month').size()

            total_positives = (
                df_p1_p2[df_p1_p2['target'] == 1]
                .groupby('month')
                .size()
            )

            tp, fp = tp.align(fp, fill_value=0)
            tp, total_positives = tp.align(total_positives, fill_value=0)

            precision_k = (tp / (tp + fp)).mean()
            recall_k = (tp / total_positives).mean()

            avg_rows = df_k.groupby('month').size().mean()
            expected_conversions = precision_k * avg_rows

            print(
                f"K={k:<4} | "
                f"Precision: {precision_k:.2%} | "
                f"Recall: {recall_k:.2%} | "
                f"Expected Conversions: {expected_conversions:.2f}"
            )
        print()

Business-Rule Selection P1P2
y_score='lifetime_month_streak_inn' ASC
K=500  | Precision: 2.79% | Recall: 25.68% | Expected Conversions: 13.93
K=1000 | Precision: 1.84% | Recall: 34.44% | Expected Conversions: 18.40
K=1500 | Precision: 1.40% | Recall: 39.71% | Expected Conversions: 21.00
K=2000 | Precision: 1.13% | Recall: 43.03% | Expected Conversions: 22.67
K=2500 | Precision: 0.99% | Recall: 47.25% | Expected Conversions: 24.80

y_score='altpay1_turnover' ASC
K=500  | Precision: 0.72% | Recall: 6.81% | Expected Conversions: 3.60
K=1000 | Precision: 0.73% | Recall: 13.66% | Expected Conversions: 7.33
K=1500 | Precision: 0.73% | Recall: 20.60% | Expected Conversions: 10.93
K=2000 | Precision: 0.70% | Recall: 26.31% | Expected Conversions: 14.00
K=2500 | Precision: 0.73% | Recall: 34.69% | Expected Conversions: 18.27

y_score='altpay2_turnover' ASC
K=500  | Precision: 0.80% | Recall: 7.41% | Expected Conversions: 4.00
K=1000 | Precision: 0.80% | Recall: 15.01% | Expected Conversions: 8.00
K=1500 | Precision: 0.77% | Recall: 22.10% | Expected Conversions: 11.60
K=2000 | Precision: 0.75% | Recall: 28.22% | Expected Conversions: 14.93
K=2500 | Precision: 0.74% | Recall: 35.21% | Expected Conversions: 18.47

y_score='altpay3_turnover' ASC
K=500  | Precision: 0.89% | Recall: 8.72% | Expected Conversions: 4.47
K=1000 | Precision: 0.86% | Recall: 16.72% | Expected Conversions: 8.60
K=1500 | Precision: 0.84% | Recall: 24.34% | Expected Conversions: 12.67
K=2000 | Precision: 0.81% | Recall: 31.11% | Expected Conversions: 16.13
K=2500 | Precision: 0.77% | Recall: 37.16% | Expected Conversions: 19.33

y_score='altpay4_turnover' ASC
K=500  | Precision: 0.76% | Recall: 7.01% | Expected Conversions: 3.80
K=1000 | Precision: 0.77% | Recall: 14.53% | Expected Conversions: 7.73
K=1500 | Precision: 0.78% | Recall: 22.33% | Expected Conversions: 11.73
K=2000 | Precision: 0.76% | Recall: 28.82% | Expected Conversions: 15.13
K=2500 | Precision: 0.75% | Recall: 35.85% | Expected Conversions: 18.73

y_score='altpay5_turnover' ASC
K=500  | Precision: 0.76% | Recall: 7.15% | Expected Conversions: 3.80
K=1000 | Precision: 0.82% | Recall: 15.61% | Expected Conversions: 8.20
K=1500 | Precision: 0.76% | Recall: 22.11% | Expected Conversions: 11.47
K=2000 | Precision: 0.76% | Recall: 28.95% | Expected Conversions: 15.20
K=2500 | Precision: 0.75% | Recall: 36.15% | Expected Conversions: 18.80

y_score='altpay6_turnover' ASC
K=500  | Precision: 0.72% | Recall: 6.70% | Expected Conversions: 3.60
K=1000 | Precision: 0.78% | Recall: 14.75% | Expected Conversions: 7.80
K=1500 | Precision: 0.78% | Recall: 22.38% | Expected Conversions: 11.67
K=2000 | Precision: 0.76% | Recall: 28.97% | Expected Conversions: 15.20
K=2500 | Precision: 0.75% | Recall: 35.76% | Expected Conversions: 18.73

y_score='cnt_trx' ASC
K=500  | Precision: 1.67% | Recall: 15.16% | Expected Conversions: 8.33
K=1000 | Precision: 1.28% | Recall: 23.50% | Expected Conversions: 12.80
K=1500 | Precision: 1.08% | Recall: 30.06% | Expected Conversions: 16.13
K=2000 | Precision: 0.95% | Recall: 35.59% | Expected Conversions: 19.00
K=2500 | Precision: 0.85% | Recall: 40.00% | Expected Conversions: 21.20

y_score='turnover' ASC
K=500  | Precision: 2.29% | Recall: 20.90% | Expected Conversions: 11.47
K=1000 | Precision: 1.36% | Recall: 25.05% | Expected Conversions: 13.60
K=1500 | Precision: 1.04% | Recall: 29.10% | Expected Conversions: 15.67
K=2000 | Precision: 0.93% | Recall: 34.44% | Expected Conversions: 18.60
K=2500 | Precision: 0.84% | Recall: 39.09% | Expected Conversions: 21.00

y_score='other_active_product_cnt' ASC
K=500  | Precision: 0.84% | Recall: 7.91% | Expected Conversions: 4.20
K=1000 | Precision: 0.85% | Recall: 15.96% | Expected Conversions: 8.47
K=1500 | Precision: 0.80% | Recall: 23.00% | Expected Conversions: 12.07
K=2000 | Precision: 0.79% | Recall: 29.74% | Expected Conversions: 15.73
K=2500 | Precision: 0.78% | Recall: 37.39% | Expected Conversions: 19.53

y_score='active_mcc_cnt' ASC
K=500  | Precision: 0.76% | Recall: 7.04% | Expected Conversions: 3.80
K=1000 | Precision: 0.84% | Recall: 16.16% | Expected Conversions: 8.40
K=1500 | Precision: 0.79% | Recall: 22.66% | Expected Conversions: 11.87
K=2000 | Precision: 0.80% | Recall: 30.49% | Expected Conversions: 16.07
K=2500 | Precision: 0.80% | Recall: 38.04% | Expected Conversions: 19.93

y_score='active_gateway_cnt' ASC
K=500  | Precision: 0.81% | Recall: 7.82% | Expected Conversions: 4.07
K=1000 | Precision: 0.86% | Recall: 16.98% | Expected Conversions: 8.60
K=1500 | Precision: 0.77% | Recall: 22.42% | Expected Conversions: 11.53
K=2000 | Precision: 0.77% | Recall: 29.60% | Expected Conversions: 15.47
K=2500 | Precision: 0.78% | Recall: 37.11% | Expected Conversions: 19.40

y_score='avg_check' ASC
K=500  | Precision: 2.43% | Recall: 22.31% | Expected Conversions: 12.13
K=1000 | Precision: 1.45% | Recall: 26.91% | Expected Conversions: 14.53
K=1500 | Precision: 1.13% | Recall: 31.61% | Expected Conversions: 17.00
K=2000 | Precision: 0.95% | Recall: 35.39% | Expected Conversions: 18.93
K=2500 | Precision: 0.84% | Recall: 39.22% | Expected Conversions: 21.07

y_score='turnover_ma_2m' ASC
K=500  | Precision: 2.27% | Recall: 20.56% | Expected Conversions: 11.33
K=1000 | Precision: 1.39% | Recall: 25.49% | Expected Conversions: 13.87
K=1500 | Precision: 1.08% | Recall: 29.75% | Expected Conversions: 16.13
K=2000 | Precision: 0.94% | Recall: 35.00% | Expected Conversions: 18.80
K=2500 | Precision: 0.86% | Recall: 40.05% | Expected Conversions: 21.40

y_score='turnover_ema_2m' ASC
K=500  | Precision: 2.28% | Recall: 20.60% | Expected Conversions: 11.40
K=1000 | Precision: 1.38% | Recall: 25.35% | Expected Conversions: 13.80
K=1500 | Precision: 1.05% | Recall: 29.16% | Expected Conversions: 15.73
K=2000 | Precision: 0.94% | Recall: 35.04% | Expected Conversions: 18.80
K=2500 | Precision: 0.86% | Recall: 39.94% | Expected Conversions: 21.40

y_score='turnover_ma_3m' ASC
K=500  | Precision: 2.25% | Recall: 20.39% | Expected Conversions: 11.27
K=1000 | Precision: 1.39% | Recall: 25.61% | Expected Conversions: 13.93
K=1500 | Precision: 1.08% | Recall: 30.15% | Expected Conversions: 16.20
K=2000 | Precision: 0.94% | Recall: 35.32% | Expected Conversions: 18.87
K=2500 | Precision: 0.86% | Recall: 40.35% | Expected Conversions: 21.53

y_score='turnover_ema_3m' ASC
K=500  | Precision: 2.27% | Recall: 20.50% | Expected Conversions: 11.33
K=1000 | Precision: 1.39% | Recall: 25.48% | Expected Conversions: 13.87
K=1500 | Precision: 1.08% | Recall: 29.94% | Expected Conversions: 16.20
K=2000 | Precision: 0.93% | Recall: 34.52% | Expected Conversions: 18.53
K=2500 | Precision: 0.86% | Recall: 40.18% | Expected Conversions: 21.47

y_score='turnover_ma_6m' ASC
K=500  | Precision: 2.31% | Recall: 20.81% | Expected Conversions: 11.53
K=1000 | Precision: 1.40% | Recall: 25.82% | Expected Conversions: 14.00
K=1500 | Precision: 1.12% | Recall: 30.99% | Expected Conversions: 16.73
K=2000 | Precision: 0.97% | Recall: 36.09% | Expected Conversions: 19.40
K=2500 | Precision: 0.86% | Recall: 40.13% | Expected Conversions: 21.53

y_score='turnover_ema_6m' ASC
K=500  | Precision: 2.31% | Recall: 20.81% | Expected Conversions: 11.53
K=1000 | Precision: 1.39% | Recall: 25.40% | Expected Conversions: 13.87
K=1500 | Precision: 1.08% | Recall: 30.12% | Expected Conversions: 16.27
K=2000 | Precision: 0.95% | Recall: 35.38% | Expected Conversions: 19.00
K=2500 | Precision: 0.86% | Recall: 40.43% | Expected Conversions: 21.60

y_score='cnt_trx_ma_2m' ASC
K=500  | Precision: 1.75% | Recall: 15.91% | Expected Conversions: 8.73
K=1000 | Precision: 1.28% | Recall: 23.37% | Expected Conversions: 12.80
K=1500 | Precision: 1.12% | Recall: 31.22% | Expected Conversions: 16.73
K=2000 | Precision: 0.97% | Recall: 36.31% | Expected Conversions: 19.33
K=2500 | Precision: 0.86% | Recall: 40.81% | Expected Conversions: 21.60

y_score='cnt_trx_ema_2m' ASC
K=500  | Precision: 1.79% | Recall: 16.12% | Expected Conversions: 8.93
K=1000 | Precision: 1.29% | Recall: 23.65% | Expected Conversions: 12.93
K=1500 | Precision: 1.10% | Recall: 30.77% | Expected Conversions: 16.53
K=2000 | Precision: 0.97% | Recall: 36.28% | Expected Conversions: 19.33
K=2500 | Precision: 0.87% | Recall: 40.98% | Expected Conversions: 21.73

y_score='cnt_trx_ma_3m' ASC
K=500  | Precision: 1.77% | Recall: 15.98% | Expected Conversions: 8.87
K=1000 | Precision: 1.29% | Recall: 23.44% | Expected Conversions: 12.87
K=1500 | Precision: 1.13% | Recall: 31.64% | Expected Conversions: 16.93
K=2000 | Precision: 0.97% | Recall: 36.32% | Expected Conversions: 19.33
K=2500 | Precision: 0.87% | Recall: 40.96% | Expected Conversions: 21.67

y_score='cnt_trx_ema_3m' ASC
K=500  | Precision: 1.79% | Recall: 16.17% | Expected Conversions: 8.93
K=1000 | Precision: 1.27% | Recall: 23.16% | Expected Conversions: 12.73
K=1500 | Precision: 1.10% | Recall: 30.53% | Expected Conversions: 16.47
K=2000 | Precision: 0.98% | Recall: 36.74% | Expected Conversions: 19.60
K=2500 | Precision: 0.86% | Recall: 40.57% | Expected Conversions: 21.53

y_score='cnt_trx_ma_6m' ASC
K=500  | Precision: 1.85% | Recall: 16.59% | Expected Conversions: 9.27
K=1000 | Precision: 1.29% | Recall: 23.92% | Expected Conversions: 12.93
K=1500 | Precision: 1.13% | Recall: 31.30% | Expected Conversions: 16.93
K=2000 | Precision: 0.98% | Recall: 36.90% | Expected Conversions: 19.60
K=2500 | Precision: 0.88% | Recall: 41.56% | Expected Conversions: 22.00

y_score='cnt_trx_ema_6m' ASC
K=500  | Precision: 1.89% | Recall: 17.00% | Expected Conversions: 9.47
K=1000 | Precision: 1.33% | Recall: 24.51% | Expected Conversions: 13.33
K=1500 | Precision: 1.13% | Recall: 31.38% | Expected Conversions: 16.93
K=2000 | Precision: 0.98% | Recall: 36.72% | Expected Conversions: 19.53
K=2500 | Precision: 0.87% | Recall: 41.19% | Expected Conversions: 21.87

y_score='avg_check_wma_2m' ASC
K=500  | Precision: 2.37% | Recall: 21.79% | Expected Conversions: 11.87
K=1000 | Precision: 1.44% | Recall: 26.50% | Expected Conversions: 14.40
K=1500 | Precision: 1.12% | Recall: 31.22% | Expected Conversions: 16.80
K=2000 | Precision: 0.97% | Recall: 36.14% | Expected Conversions: 19.40
K=2500 | Precision: 0.82% | Recall: 38.37% | Expected Conversions: 20.60

y_score='avg_check_wma_3m' ASC
K=500  | Precision: 2.45% | Recall: 22.65% | Expected Conversions: 12.27
K=1000 | Precision: 1.45% | Recall: 26.86% | Expected Conversions: 14.53
K=1500 | Precision: 1.13% | Recall: 31.72% | Expected Conversions: 17.00
K=2000 | Precision: 0.93% | Recall: 34.81% | Expected Conversions: 18.67
K=2500 | Precision: 0.83% | Recall: 38.50% | Expected Conversions: 20.73

y_score='avg_check_wma_6m' ASC
K=500  | Precision: 2.40% | Recall: 22.13% | Expected Conversions: 12.00
K=1000 | Precision: 1.41% | Recall: 26.14% | Expected Conversions: 14.13
K=1500 | Precision: 1.09% | Recall: 30.56% | Expected Conversions: 16.40
K=2000 | Precision: 0.95% | Recall: 35.16% | Expected Conversions: 18.93
K=2500 | Precision: 0.82% | Recall: 38.14% | Expected Conversions: 20.53

y_score='turnover_cv_2m' ASC
K=500  | Precision: 2.25% | Recall: 20.78% | Expected Conversions: 11.27
K=1000 | Precision: 1.41% | Recall: 26.39% | Expected Conversions: 14.07
K=1500 | Precision: 1.11% | Recall: 31.41% | Expected Conversions: 16.67
K=2000 | Precision: 0.95% | Recall: 36.12% | Expected Conversions: 19.00
K=2500 | Precision: 0.85% | Recall: 40.19% | Expected Conversions: 21.13

y_score='turnover_cv_3m' ASC
K=500  | Precision: 2.28% | Recall: 20.85% | Expected Conversions: 11.40
K=1000 | Precision: 1.43% | Recall: 26.45% | Expected Conversions: 14.27
K=1500 | Precision: 1.08% | Recall: 30.19% | Expected Conversions: 16.20
K=2000 | Precision: 0.94% | Recall: 35.27% | Expected Conversions: 18.73
K=2500 | Precision: 0.82% | Recall: 38.80% | Expected Conversions: 20.47

y_score='turnover_cv_6m' ASC
K=500  | Precision: 2.35% | Recall: 21.45% | Expected Conversions: 11.73
K=1000 | Precision: 1.33% | Recall: 24.25% | Expected Conversions: 13.27
K=1500 | Precision: 1.00% | Recall: 27.58% | Expected Conversions: 14.93
K=2000 | Precision: 0.87% | Recall: 32.65% | Expected Conversions: 17.47
K=2500 | Precision: 0.77% | Recall: 36.29% | Expected Conversions: 19.20

y_score='turnover_change_to_prev_month' ASC
K=500  | Precision: 0.41% | Recall: 4.07% | Expected Conversions: 2.07
K=1000 | Precision: 0.38% | Recall: 7.48% | Expected Conversions: 3.80
K=1500 | Precision: 0.42% | Recall: 12.20% | Expected Conversions: 6.27
K=2000 | Precision: 0.61% | Recall: 23.39% | Expected Conversions: 12.13
K=2500 | Precision: 0.76% | Recall: 35.70% | Expected Conversions: 19.07

y_score='cnt_trx_change_to_prev_month' ASC
K=500  | Precision: 0.40% | Recall: 3.93% | Expected Conversions: 2.00
K=1000 | Precision: 0.39% | Recall: 7.69% | Expected Conversions: 3.87
K=1500 | Precision: 0.40% | Recall: 12.02% | Expected Conversions: 6.00
K=2000 | Precision: 0.57% | Recall: 22.33% | Expected Conversions: 11.33
K=2500 | Precision: 0.75% | Recall: 35.18% | Expected Conversions: 18.80

y_score='avg_check_change_to_prev_month' ASC
K=500  | Precision: 0.69% | Recall: 7.04% | Expected Conversions: 3.47
K=1000 | Precision: 0.55% | Recall: 10.97% | Expected Conversions: 5.53
K=1500 | Precision: 0.54% | Recall: 16.15% | Expected Conversions: 8.13
K=2000 | Precision: 0.77% | Recall: 28.71% | Expected Conversions: 15.47
K=2500 | Precision: 0.85% | Recall: 40.39% | Expected Conversions: 21.20

y_score='turnover_change_to_turnover_ma_2m' ASC
K=500  | Precision: 0.41% | Recall: 4.07% | Expected Conversions: 2.07
K=1000 | Precision: 0.38% | Recall: 7.48% | Expected Conversions: 3.80
K=1500 | Precision: 0.42% | Recall: 12.20% | Expected Conversions: 6.27
K=2000 | Precision: 0.61% | Recall: 23.39% | Expected Conversions: 12.13
K=2500 | Precision: 0.76% | Recall: 35.70% | Expected Conversions: 19.07

y_score='turnover_change_to_turnover_ma_3m' ASC
K=500  | Precision: 0.48% | Recall: 4.55% | Expected Conversions: 2.40
K=1000 | Precision: 0.38% | Recall: 7.50% | Expected Conversions: 3.80
K=1500 | Precision: 0.40% | Recall: 11.99% | Expected Conversions: 6.07
K=2000 | Precision: 0.56% | Recall: 20.92% | Expected Conversions: 11.13
K=2500 | Precision: 0.69% | Recall: 32.05% | Expected Conversions: 17.33

y_score='turnover_change_to_turnover_ma_6m' ASC
K=500  | Precision: 0.45% | Recall: 4.43% | Expected Conversions: 2.27
K=1000 | Precision: 0.42% | Recall: 8.16% | Expected Conversions: 4.20
K=1500 | Precision: 0.41% | Recall: 12.14% | Expected Conversions: 6.13
K=2000 | Precision: 0.53% | Recall: 19.44% | Expected Conversions: 10.53
K=2500 | Precision: 0.66% | Recall: 30.51% | Expected Conversions: 16.60

y_score='turnover_change_to_turnover_ema_2m' ASC
K=500  | Precision: 0.45% | Recall: 4.52% | Expected Conversions: 2.27
K=1000 | Precision: 0.40% | Recall: 7.92% | Expected Conversions: 4.00
K=1500 | Precision: 0.41% | Recall: 11.89% | Expected Conversions: 6.13
K=2000 | Precision: 0.55% | Recall: 21.13% | Expected Conversions: 11.00
K=2500 | Precision: 0.71% | Recall: 32.84% | Expected Conversions: 17.67

y_score='turnover_change_to_turnover_ema_3m' ASC
K=500  | Precision: 0.51% | Recall: 5.13% | Expected Conversions: 2.53
K=1000 | Precision: 0.43% | Recall: 8.41% | Expected Conversions: 4.33
K=1500 | Precision: 0.39% | Recall: 11.38% | Expected Conversions: 5.87
K=2000 | Precision: 0.51% | Recall: 19.54% | Expected Conversions: 10.20
K=2500 | Precision: 0.68% | Recall: 31.44% | Expected Conversions: 17.00

y_score='turnover_change_to_turnover_ema_6m' ASC
K=500  | Precision: 0.48% | Recall: 4.73% | Expected Conversions: 2.40
K=1000 | Precision: 0.42% | Recall: 8.12% | Expected Conversions: 4.20
K=1500 | Precision: 0.40% | Recall: 11.73% | Expected Conversions: 5.93
K=2000 | Precision: 0.44% | Recall: 17.08% | Expected Conversions: 8.80
K=2500 | Precision: 0.64% | Recall: 29.82% | Expected Conversions: 16.00

y_score='cnt_trx_change_to_cnt_trx_ma_2m' ASC
K=500  | Precision: 0.40% | Recall: 3.93% | Expected Conversions: 2.00
K=1000 | Precision: 0.39% | Recall: 7.69% | Expected Conversions: 3.87
K=1500 | Precision: 0.40% | Recall: 12.02% | Expected Conversions: 6.00
K=2000 | Precision: 0.57% | Recall: 22.33% | Expected Conversions: 11.33
K=2500 | Precision: 0.75% | Recall: 35.18% | Expected Conversions: 18.80

y_score='cnt_trx_change_to_cnt_trx_ma_3m' ASC
K=500  | Precision: 0.39% | Recall: 3.79% | Expected Conversions: 1.93
K=1000 | Precision: 0.42% | Recall: 8.33% | Expected Conversions: 4.20
K=1500 | Precision: 0.38% | Recall: 11.36% | Expected Conversions: 5.67
K=2000 | Precision: 0.54% | Recall: 21.11% | Expected Conversions: 10.87
K=2500 | Precision: 0.69% | Recall: 31.72% | Expected Conversions: 17.13

y_score='cnt_trx_change_to_cnt_trx_ma_6m' ASC
K=500  | Precision: 0.36% | Recall: 3.56% | Expected Conversions: 1.80
K=1000 | Precision: 0.40% | Recall: 8.05% | Expected Conversions: 4.00
K=1500 | Precision: 0.39% | Recall: 11.58% | Expected Conversions: 5.80
K=2000 | Precision: 0.47% | Recall: 17.87% | Expected Conversions: 9.40
K=2500 | Precision: 0.63% | Recall: 29.70% | Expected Conversions: 15.87

y_score='cnt_trx_change_to_cnt_trx_ema_2m' ASC
K=500  | Precision: 0.43% | Recall: 4.20% | Expected Conversions: 2.13
K=1000 | Precision: 0.40% | Recall: 8.15% | Expected Conversions: 4.00
K=1500 | Precision: 0.38% | Recall: 11.33% | Expected Conversions: 5.73
K=2000 | Precision: 0.49% | Recall: 19.58% | Expected Conversions: 9.87
K=2500 | Precision: 0.70% | Recall: 32.25% | Expected Conversions: 17.40

y_score='cnt_trx_change_to_cnt_trx_ema_3m' ASC
K=500  | Precision: 0.39% | Recall: 3.83% | Expected Conversions: 1.93
K=1000 | Precision: 0.39% | Recall: 7.79% | Expected Conversions: 3.87
K=1500 | Precision: 0.37% | Recall: 11.16% | Expected Conversions: 5.60
K=2000 | Precision: 0.47% | Recall: 19.13% | Expected Conversions: 9.47
K=2500 | Precision: 0.69% | Recall: 31.91% | Expected Conversions: 17.20

y_score='cnt_trx_change_to_cnt_trx_ema_6m' ASC
K=500  | Precision: 0.33% | Recall: 3.17% | Expected Conversions: 1.67
K=1000 | Precision: 0.41% | Recall: 8.06% | Expected Conversions: 4.07
K=1500 | Precision: 0.38% | Recall: 11.34% | Expected Conversions: 5.67
K=2000 | Precision: 0.39% | Recall: 15.61% | Expected Conversions: 7.87
K=2500 | Precision: 0.63% | Recall: 29.72% | Expected Conversions: 15.87

y_score='avg_check_change_to_avg_check_wma_2m' ASC
K=500  | Precision: 0.61% | Recall: 6.06% | Expected Conversions: 3.07
K=1000 | Precision: 0.55% | Recall: 10.93% | Expected Conversions: 5.47
K=1500 | Precision: 0.53% | Recall: 15.89% | Expected Conversions: 8.00
K=2000 | Precision: 0.69% | Recall: 25.93% | Expected Conversions: 13.87
K=2500 | Precision: 0.86% | Recall: 40.76% | Expected Conversions: 21.53

y_score='avg_check_change_to_avg_check_wma_3m' ASC
K=500  | Precision: 0.60% | Recall: 6.00% | Expected Conversions: 3.00
K=1000 | Precision: 0.54% | Recall: 10.75% | Expected Conversions: 5.40
K=1500 | Precision: 0.49% | Recall: 14.45% | Expected Conversions: 7.33
K=2000 | Precision: 0.70% | Recall: 26.12% | Expected Conversions: 14.00
K=2500 | Precision: 0.86% | Recall: 40.63% | Expected Conversions: 21.40

y_score='avg_check_change_to_avg_check_wma_6m' ASC
K=500  | Precision: 0.61% | Recall: 5.94% | Expected Conversions: 3.07
K=1000 | Precision: 0.55% | Recall: 10.63% | Expected Conversions: 5.47
K=1500 | Precision: 0.48% | Recall: 14.30% | Expected Conversions: 7.27
K=2000 | Precision: 0.71% | Recall: 25.95% | Expected Conversions: 14.13
K=2500 | Precision: 0.85% | Recall: 39.80% | Expected Conversions: 21.13

y_score='lifetime_month_streak_inn' DESC
K=500  | Precision: 0.31% | Recall: 2.93% | Expected Conversions: 1.53
K=1000 | Precision: 0.34% | Recall: 6.52% | Expected Conversions: 3.40
K=1500 | Precision: 0.29% | Recall: 8.53% | Expected Conversions: 4.40
K=2000 | Precision: 0.31% | Recall: 12.35% | Expected Conversions: 6.27

### Logistic Regression

Подготовим данные для обучения Логистической регрессии

In [7]:
df_p1_p2_preprocessed = df_p1_p2.copy()

df_p1_p2_preprocessed['months_since_last_active_months'] = (
    (df_p1_p2_preprocessed['month'].dt.year - df_p1_p2_preprocessed['last_active_month_inn'].dt.year) * 12 +
    (df_p1_p2_preprocessed['month'].dt.month - df_p1_p2_preprocessed['last_active_month_inn'].dt.month)
)

df_p1_p2_preprocessed["months_since_first_trx"] = (
    (df_p1_p2_preprocessed["month"].dt.year - df_p1_p2_preprocessed["first_trx_month_inn"].dt.year) * 12 +
    (df_p1_p2_preprocessed["month"].dt.month - df_p1_p2_preprocessed["first_trx_month_inn"].dt.month)
)

df_p1_p2_preprocessed["has_p3"] = df_p1_p2_preprocessed["first_month_p3"].notna()

df_p1_p2_preprocessed["has_altpay5"] = df_p1_p2_preprocessed["first_month_altpay5"].notna()

cols_to_drop = [
    'inn',
    "last_active_month_inn",
    "first_trx_month_inn",
    "top_mcc_group_inn",
    "who_is_this_first_inn",
    "first_month_p3",
    "first_month_altpay5",
]

df_p1_p2_preprocessed = (
    df_p1_p2_preprocessed
    .sort_values(by='month')
    .reset_index(drop=True)
    .drop(columns=cols_to_drop)
)

df_p1_p2_preprocessed = pd.get_dummies(df_p1_p2_preprocessed)

In [38]:
train = df_p1_p2_preprocessed.loc[df_p1_p2_preprocessed['month'] < '2025-12-01'] # 80%
test = df_p1_p2_preprocessed.loc[df_p1_p2_preprocessed['month'] >= '2025-12-01'] # 20%

X_train = train.drop(columns=['target', 'month'])
y_train = train['target']

X_test = test.drop(columns=['target', 'month'])
y_test = test['target']

In [39]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=100_000)

lr.fit(X_train, y_train)

test['lr_proba'] = lr.predict_proba(X_test)[:, 1]

In [40]:
pd.DataFrame(lr.coef_[0], index=lr.feature_names_in_).sort_values(by=0, ascending=False).head(10)

                                        0
is_first_trx_month                 1.5367
is_relevant_mcc_altpay5            0.8984
is_relevant_turnover_altpay5       0.5304
rule_flag                          0.3447
turnover_change_to_turnover_ma_6m  0.2610
altpay3_turnover                   0.2549
cnt_trx                            0.1824
cnt_trx_ma_6m                      0.1747
cnt_trx_ma_2m                      0.1641
cnt_trx_ma_3m                      0.1632

In [41]:
pd.DataFrame(lr.coef_[0], index=lr.feature_names_in_).sort_values(by=0, ascending=True).head(10)

                                           0
inn_status_Churn                     -2.4655
has_termination_start                -1.3104
is_left_time_border                  -0.9293
avg_check_change_to_avg_check_wma_6m -0.6079
turnover_cv_2m                       -0.5172
inn_status_Active                    -0.5165
inn_status_New Churn                 -0.4832
turnover_ema_2m                      -0.3905
turnover_ma_6m                       -0.3815
turnover_ma_2m                       -0.3613

In [42]:
k_values = [500, 1000, 1500, 2000, 2500]
y_score = 'lr_proba'

print(f"Logistic Regression P1P2, y_score='{y_score}'")

for k in k_values:
    df_k = (
        test
        .sort_values(by=y_score, ascending=False)
        .groupby('month')
        .head(k)
    )

    tp = df_k[df_k['target'] == 1].groupby('month').size()
    fp = df_k[df_k['target'] == 0].groupby('month').size()

    total_positives = (
        test[test['target'] == 1]
        .groupby('month')
        .size()
    )

    tp, fp = tp.align(fp, fill_value=0)
    tp, total_positives = tp.align(total_positives, fill_value=0)

    precision_k = (tp / (tp + fp)).mean()
    recall_k = (tp / total_positives).mean()

    avg_rows = df_k.groupby('month').size().mean()
    expected_conversions = precision_k * avg_rows

    print(
        f"K={k:<4} | "
        f"Precision: {precision_k:.2%} | "
        f"Recall: {recall_k:.2%} | "
        f"Expected Conversions: {expected_conversions:.2f}"
    )

Logistic Regression P1P2, y_score='lr_proba'
K=500  | Precision: 3.40% | Recall: 29.56% | Expected Conversions: 17.00
K=1000 | Precision: 2.17% | Recall: 37.72% | Expected Conversions: 21.67
K=1500 | Precision: 1.67% | Recall: 43.35% | Expected Conversions: 25.00
K=2000 | Precision: 1.42% | Recall: 49.32% | Expected Conversions: 28.33
K=2500 | Precision: 1.20% | Recall: 52.18% | Expected Conversions: 30.00

### LightGBM

In [ ]:
import lightgbm as lgb

### CatBoost

## P3

### Случайный отбор

In [33]:
k_values = [500, 1000, 1500, 2000, 2500]

target_monthly = df_p3.groupby('month').target.sum()
month_sizes = df_p3.groupby('month').size()

precision = (target_monthly / month_sizes).mean()  # macro average

print("Random Selection P1P2")

for k in k_values:
    coverage = (k / month_sizes).mean()
    expected_conversions = precision * k

    print(
        f"K={k:<4} | "
        f"Precision: {precision:.2%} | "
        f"Coverage: {coverage:.2%} | "
        f"Expected Conversions: {expected_conversions:.2f}"
    )

Random Selection P1P2
K=500  | Precision: 0.01% | Coverage: 1.94% | Expected Conversions: 0.03
K=1000 | Precision: 0.01% | Coverage: 3.87% | Expected Conversions: 0.07
K=1500 | Precision: 0.01% | Coverage: 5.81% | Expected Conversions: 0.10
K=2000 | Precision: 0.01% | Coverage: 7.74% | Expected Conversions: 0.14
K=2500 | Precision: 0.01% | Coverage: 9.68% | Expected Conversions: 0.17

### Business-Rule

Критерии релевантности:
- Отсутствие подключённого продукта `P3`
- Статус `'Active'`, `'Reborn'`
- Релевантные MCC (флаг `is_relevant_mcc_p3`)
- Группа MCC `!= 'Charity'`

In [34]:
def add_rule_flag_p3(df: pd.DataFrame) -> pd.DataFrame:
    active_statuses = ["Active", "Reborn"]
    banned_mcc_groups = ["Charity"]

    df = df.copy()
    
    df["rule_flag"] = (
        df["inn_status"].isin(active_statuses)
        & ~df["top_mcc_group_inn"].isin(banned_mcc_groups)
        & df["is_relevant_mcc_p3"]
    ).astype("int8")

    return df


df_p3 = add_rule_flag_p3(df_p3)

In [35]:
k_values = [500, 1000, 1500, 2000, 2500]
y_score = 'turnover'

print(f"Business-Rule Selection P3, y_score='{y_score}'")

for k in k_values:
    df_k = (
        df_p3.query('rule_flag == 1')
        .sort_values(by=y_score, ascending=False)
        .groupby('month')
        .head(k)
    )

    tp = df_k[df_k['target'] == 1].groupby('month').size()
    fp = df_k[df_k['target'] == 0].groupby('month').size()

    total_positives = (
        df_p3[df_p3['target'] == 1]
        .groupby('month')
        .size()
    )

    tp, fp = tp.align(fp, fill_value=0)
    tp, total_positives = tp.align(total_positives, fill_value=0)

    precision_k = (tp / (tp + fp)).mean()
    recall_k = (tp / total_positives).mean()

    avg_rows = df_k.groupby('month').size().mean()
    expected_conversions = precision_k * avg_rows

    print(
        f"K={k:<4} | "
        f"Precision: {precision_k:.2%} | "
        f"Recall: {recall_k:.2%} | "
        f"Expected Conversions: {expected_conversions:.2f}"
    )

Business-Rule Selection P3, y_score='turnover'
K=500  | Precision: 0.03% | Recall: 7.58% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 10.61% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 28.79% | Expected Conversions: 0.47
K=2500 | Precision: 0.02% | Recall: 31.82% | Expected Conversions: 0.53

Попробуем также как с `P1P2` пересмотреть метрику ранжирования

In [36]:
numeric_features = [col for col in df_p3.select_dtypes(include=['number']).columns if col not in ('target', 'rule_flag')]

k_values = [500, 1000, 1500, 2000, 2500]

print(f"Business-Rule Selection P3")

for asc in (True, False):
    for feature in numeric_features:
        y_score = feature
        print(f"y_score='{y_score}' {'ASC' if asc else 'DESC'}")
        for k in k_values:
            df_k = (
                df_p3.query('rule_flag == 1')
                .sort_values(by=y_score, ascending=asc)
                .groupby('month')
                .head(k)
            )

            tp = df_k[df_k['target'] == 1].groupby('month').size()
            fp = df_k[df_k['target'] == 0].groupby('month').size()

            total_positives = (
                df_p3[df_p3['target'] == 1]
                .groupby('month')
                .size()
            )

            tp, fp = tp.align(fp, fill_value=0)
            tp, total_positives = tp.align(total_positives, fill_value=0)

            precision_k = (tp / (tp + fp)).mean()
            recall_k = (tp / total_positives).mean()

            avg_rows = df_k.groupby('month').size().mean()
            expected_conversions = precision_k * avg_rows

            print(
                f"K={k:<4} | "
                f"Precision: {precision_k:.2%} | "
                f"Recall: {recall_k:.2%} | "
                f"Expected Conversions: {expected_conversions:.2f}"
            )
        print()

Business-Rule Selection P3
y_score='lifetime_month_streak_inn' ASC
K=500  | Precision: 0.01% | Recall: 2.27% | Expected Conversions: 0.07
K=1000 | Precision: 0.01% | Recall: 2.27% | Expected Conversions: 0.07
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.02% | Recall: 12.12% | Expected Conversions: 0.33
K=2500 | Precision: 0.02% | Recall: 25.76% | Expected Conversions: 0.47

y_score='altpay1_turnover' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1500 | Precision: 0.01% | Recall: 6.06% | Expected Conversions: 0.13
K=2000 | Precision: 0.01% | Recall: 12.12% | Expected Conversions: 0.27
K=2500 | Precision: 0.01% | Recall: 14.39% | Expected Conversions: 0.33

y_score='altpay2_turnover' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 12.12% | Expected Conversions: 0.27
K=2000 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40

y_score='altpay3_turnover' ASC
K=500  | Precision: 0.01% | Recall: 3.03% | Expected Conversions: 0.07
K=1000 | Precision: 0.01% | Recall: 6.06% | Expected Conversions: 0.13
K=1500 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.20
K=2000 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.20
K=2500 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.20

y_score='altpay4_turnover' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40

y_score='altpay5_turnover' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40

y_score='altpay6_turnover' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40

y_score='cnt_trx' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2500 | Precision: 0.01% | Recall: 20.45% | Expected Conversions: 0.33

y_score='turnover' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.02% | Recall: 13.64% | Expected Conversions: 0.33
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='other_active_product_cnt' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 12.12% | Expected Conversions: 0.27
K=2000 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 17.42% | Expected Conversions: 0.40

y_score='active_mcc_cnt' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=1500 | Precision: 0.02% | Recall: 13.64% | Expected Conversions: 0.27
K=2000 | Precision: 0.01% | Recall: 13.64% | Expected Conversions: 0.27
K=2500 | Precision: 0.01% | Recall: 15.91% | Expected Conversions: 0.33

y_score='active_gateway_cnt' ASC
K=500  | Precision: 0.03% | Recall: 6.06% | Expected Conversions: 0.13
K=1000 | Precision: 0.01% | Recall: 6.06% | Expected Conversions: 0.13
K=1500 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.20
K=2000 | Precision: 0.01% | Recall: 15.15% | Expected Conversions: 0.27
K=2500 | Precision: 0.02% | Recall: 26.52% | Expected Conversions: 0.40

y_score='avg_check' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 6.82% | Expected Conversions: 0.13
K=1500 | Precision: 0.03% | Recall: 25.76% | Expected Conversions: 0.40
K=2000 | Precision: 0.03% | Recall: 30.30% | Expected Conversions: 0.53
K=2500 | Precision: 0.02% | Recall: 33.33% | Expected Conversions: 0.60

y_score='turnover_ma_2m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.02% | Recall: 13.64% | Expected Conversions: 0.33
K=2500 | Precision: 0.02% | Recall: 25.76% | Expected Conversions: 0.47

y_score='turnover_ema_2m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.02% | Recall: 13.64% | Expected Conversions: 0.33
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='turnover_ma_3m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.02% | Recall: 13.64% | Expected Conversions: 0.33
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='turnover_ema_3m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 6.82% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='turnover_ma_6m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 6.82% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='turnover_ema_6m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.02% | Recall: 13.64% | Expected Conversions: 0.33
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='cnt_trx_ma_2m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='cnt_trx_ema_2m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.01% | Recall: 9.09% | Expected Conversions: 0.20
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='cnt_trx_ma_3m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='cnt_trx_ema_3m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2500 | Precision: 0.01% | Recall: 13.64% | Expected Conversions: 0.33

y_score='cnt_trx_ma_6m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2500 | Precision: 0.01% | Recall: 20.45% | Expected Conversions: 0.33

y_score='cnt_trx_ema_6m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1500 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=2000 | Precision: 0.01% | Recall: 6.82% | Expected Conversions: 0.20
K=2500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.40

y_score='avg_check_wma_2m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 6.82% | Expected Conversions: 0.13
K=1500 | Precision: 0.02% | Recall: 22.73% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 28.79% | Expected Conversions: 0.47
K=2500 | Precision: 0.02% | Recall: 33.33% | Expected Conversions: 0.60

y_score='avg_check_wma_3m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 6.82% | Expected Conversions: 0.13
K=1500 | Precision: 0.02% | Recall: 16.67% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 28.79% | Expected Conversions: 0.47
K=2500 | Precision: 0.02% | Recall: 33.33% | Expected Conversions: 0.60

y_score='avg_check_wma_6m' ASC
K=500  | Precision: 0.00% | Recall: 0.00% | Expected Conversions: 0.00
K=1000 | Precision: 0.01% | Recall: 2.27% | Expected Conversions: 0.07
K=1500 | Precision: 0.02% | Recall: 16.67% | Expected Conversions: 0.33
K=2000 | Precision: 0.03% | Recall: 30.30% | Expected Conversions: 0.53
K=2500 | Precision: 0.02% | Recall: 33.33% | Expected Conversions: 0.60

y_score='turnover_cv_2m' ASC
K=500  | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.07
K=1000 | Precision: 0.03% | Recall: 20.45% | Expected Conversions: 0.27
K=1500 | Precision: 0.02% | Recall: 23.48% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 26.52% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 29.55% | Expected Conversions: 0.47

y_score='turnover_cv_3m' ASC
K=500  | Precision: 0.03% | Recall: 7.58% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 9.85% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 23.48% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 26.52% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 29.55% | Expected Conversions: 0.47

y_score='turnover_cv_6m' ASC
K=500  | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.07
K=1000 | Precision: 0.03% | Recall: 14.39% | Expected Conversions: 0.27
K=1500 | Precision: 0.02% | Recall: 23.48% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 23.48% | Expected Conversions: 0.33
K=2500 | Precision: 0.02% | Recall: 29.55% | Expected Conversions: 0.47

y_score='turnover_change_to_prev_month' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 15.15% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 31.06% | Expected Conversions: 0.53

y_score='cnt_trx_change_to_prev_month' ASC
K=500  | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=1500 | Precision: 0.02% | Recall: 10.61% | Expected Conversions: 0.27
K=2000 | Precision: 0.02% | Recall: 24.24% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 31.06% | Expected Conversions: 0.53

y_score='avg_check_change_to_prev_month' ASC
K=500  | Precision: 0.04% | Recall: 7.58% | Expected Conversions: 0.20
K=1000 | Precision: 0.03% | Recall: 12.12% | Expected Conversions: 0.27
K=1500 | Precision: 0.02% | Recall: 16.67% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 31.06% | Expected Conversions: 0.53

y_score='turnover_change_to_turnover_ma_2m' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 15.15% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 31.06% | Expected Conversions: 0.53

y_score='turnover_change_to_turnover_ma_3m' ASC
K=500  | Precision: 0.04% | Recall: 7.58% | Expected Conversions: 0.20
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 10.61% | Expected Conversions: 0.27
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 28.79% | Expected Conversions: 0.47

y_score='turnover_change_to_turnover_ma_6m' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40

y_score='turnover_change_to_turnover_ema_2m' ASC
K=500  | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 10.61% | Expected Conversions: 0.27
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 28.79% | Expected Conversions: 0.47

y_score='turnover_change_to_turnover_ema_3m' ASC
K=500  | Precision: 0.04% | Recall: 7.58% | Expected Conversions: 0.20
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40

y_score='turnover_change_to_turnover_ema_6m' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40

y_score='cnt_trx_change_to_cnt_trx_ma_2m' ASC
K=500  | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13
K=1500 | Precision: 0.02% | Recall: 10.61% | Expected Conversions: 0.27
K=2000 | Precision: 0.02% | Recall: 24.24% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 31.06% | Expected Conversions: 0.53

y_score='cnt_trx_change_to_cnt_trx_ma_3m' ASC
K=500  | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 10.61% | Expected Conversions: 0.27
K=2000 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.27
K=2500 | Precision: 0.02% | Recall: 28.79% | Expected Conversions: 0.47

y_score='cnt_trx_change_to_cnt_trx_ma_6m' ASC
K=500  | Precision: 0.04% | Recall: 7.58% | Expected Conversions: 0.20
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.27
K=2500 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40

y_score='cnt_trx_change_to_cnt_trx_ema_2m' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.02% | Recall: 10.61% | Expected Conversions: 0.27
K=2000 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.27
K=2500 | Precision: 0.02% | Recall: 31.06% | Expected Conversions: 0.53

y_score='cnt_trx_change_to_cnt_trx_ema_3m' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.27
K=2500 | Precision: 0.02% | Recall: 28.79% | Expected Conversions: 0.47

y_score='cnt_trx_change_to_cnt_trx_ema_6m' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.02% | Recall: 7.58% | Expected Conversions: 0.20
K=1500 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.20
K=2000 | Precision: 0.01% | Recall: 10.61% | Expected Conversions: 0.27
K=2500 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40

y_score='avg_check_change_to_avg_check_wma_2m' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.03% | Recall: 12.12% | Expected Conversions: 0.27
K=1500 | Precision: 0.02% | Recall: 16.67% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 31.06% | Expected Conversions: 0.53

y_score='avg_check_change_to_avg_check_wma_3m' ASC
K=500  | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1000 | Precision: 0.03% | Recall: 13.64% | Expected Conversions: 0.27
K=1500 | Precision: 0.02% | Recall: 16.67% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 21.97% | Expected Conversions: 0.47

y_score='avg_check_change_to_avg_check_wma_6m' ASC
K=500  | Precision: 0.03% | Recall: 4.55% | Expected Conversions: 0.13
K=1000 | Precision: 0.03% | Recall: 12.12% | Expected Conversions: 0.27
K=1500 | Precision: 0.02% | Recall: 16.67% | Expected Conversions: 0.33
K=2000 | Precision: 0.02% | Recall: 19.70% | Expected Conversions: 0.40
K=2500 | Precision: 0.02% | Recall: 33.33% | Expected Conversions: 0.60

y_score='lifetime_month_streak_inn' DESC
K=500  | Precision: 0.01% | Recall: 3.03% | Expected Conversions: 0.07
K=1000 | Precision: 0.01% | Recall: 7.58% | Expected Conversions: 0.13
K=1500 | Precision: 0.02% | Recall: 21.21% | Expected Conversions: 0.27
K=2000 | Precision: 0.02% | Recall: 28.79% | Expected Conversions: 0.47
K=2500 | Precision: 0.02% | Recall: 31.06% | Expected Conversions: 0.53

y_score='altpay1_turnover' DESC
K=500  | Precision: 0.01% | Recall: 1.52% | Expected Conversions: 0.07
K=1000 | Precision: 0.01% | Recall: 4.55% | Expected Conversions: 0.13

## Altpay5

### Случайный отбор

In [37]:
k_values = [500, 1000, 1500, 2000, 2500]

target_monthly = df_altpay5.groupby('month').target.sum()
month_sizes = df_altpay5.groupby('month').size()

precision = (target_monthly / month_sizes).mean()  # macro average

print("Random Selection P1P2")

for k in k_values:
    coverage = (k / month_sizes).mean()
    expected_conversions = precision * k

    print(
        f"K={k:<4} | "
        f"Precision: {precision:.2%} | "
        f"Coverage: {coverage:.2%} | "
        f"Expected Conversions: {expected_conversions:.2f}"
    )

Random Selection P1P2
K=500  | Precision: 0.14% | Coverage: 1.97% | Expected Conversions: 0.68
K=1000 | Precision: 0.14% | Coverage: 3.94% | Expected Conversions: 1.35
K=1500 | Precision: 0.14% | Coverage: 5.91% | Expected Conversions: 2.03
K=2000 | Precision: 0.14% | Coverage: 7.88% | Expected Conversions: 2.70
K=2500 | Precision: 0.14% | Coverage: 9.85% | Expected Conversions: 3.38

### Business-Rule

Критерии релевантности:
- Отсутствие подключённого продукта `Altpay5`
- Статус `'Active'`, `'Reborn'`
- Только релевантные MCC (флаг `is_relevant_mcc_altpay5`)
- Минимальный порог оборота (флаг `is_relevant_turnover_altpay5`)

In [38]:
def add_rule_flag_altpay5(df: pd.DataFrame) -> pd.DataFrame:
    active_statuses = ["Active", "Reborn"]

    df = df.copy()
    
    df["rule_flag"] = (
        df["inn_status"].isin(active_statuses)
        & df["is_relevant_mcc_altpay5"]
        & df["is_relevant_turnover_altpay5"]
    ).astype("int8")

    return df


df_altpay5 = add_rule_flag_altpay5(df_altpay5)

In [39]:
k_values = [500, 1000, 1500, 2000, 2500]
y_score = 'turnover'

print(f"Business-Rule Selection Altpay5, y_score='{y_score}'")

for k in k_values:
    df_k = (
        df_altpay5.query('rule_flag == 1')
        .sort_values(by=y_score, ascending=False)
        .groupby('month')
        .head(k)
    )

    tp = df_k[df_k['target'] == 1].groupby('month').size()
    fp = df_k[df_k['target'] == 0].groupby('month').size()

    total_positives = (
        df_altpay5[df_altpay5['target'] == 1]
        .groupby('month')
        .size()
    )

    tp, fp = tp.align(fp, fill_value=0)
    tp, total_positives = tp.align(total_positives, fill_value=0)

    precision_k = (tp / (tp + fp)).mean()
    recall_k = (tp / total_positives).mean()

    avg_rows = df_k.groupby('month').size().mean()
    expected_conversions = precision_k * avg_rows

    print(
        f"K={k:<4} | "
        f"Precision: {precision_k:.2%} | "
        f"Recall: {recall_k:.2%} | "
        f"Expected Conversions: {expected_conversions:.2f}"
    )

Business-Rule Selection Altpay5, y_score='turnover'
K=500  | Precision: 1.00% | Recall: 16.40% | Expected Conversions: 5.00
K=1000 | Precision: 0.90% | Recall: 27.94% | Expected Conversions: 9.00
K=1500 | Precision: 0.79% | Recall: 36.16% | Expected Conversions: 11.80
K=2000 | Precision: 0.76% | Recall: 45.31% | Expected Conversions: 15.20
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

Пересмотрим метрику ранжирования

In [ ]:
numeric_features = [col for col in df_altpay5.select_dtypes(include=['number']).columns if col not in ('target', 'rule_flag', 'altpay5_turnover')]

k_values = [500, 1000, 1500, 2000, 2500]

print(f"Business-Rule Selection Altpay5")

for asc in (True, False):
    for feature in numeric_features:
        y_score = feature
        print(f"y_score='{y_score}' {'ASC' if asc else 'DESC'}")
        for k in k_values:
            df_k = (
                df_altpay5.query('rule_flag == 1')
                .sort_values(by=y_score, ascending=asc)
                .groupby('month')
                .head(k)
            )

            tp = df_k[df_k['target'] == 1].groupby('month').size()
            fp = df_k[df_k['target'] == 0].groupby('month').size()

            total_positives = (
                df_altpay5[df_altpay5['target'] == 1]
                .groupby('month')
                .size()
            )

            tp, fp = tp.align(fp, fill_value=0)
            tp, total_positives = tp.align(total_positives, fill_value=0)

            precision_k = (tp / (tp + fp)).mean()
            recall_k = (tp / total_positives).mean()

            avg_rows = df_k.groupby('month').size().mean()
            expected_conversions = precision_k * avg_rows

            print(
                f"K={k:<4} | "
                f"Precision: {precision_k:.2%} | "
                f"Recall: {recall_k:.2%} | "
                f"Expected Conversions: {expected_conversions:.2f}"
            )
        print()

Business-Rule Selection P3
y_score='lifetime_month_streak_inn' ASC
K=500  | Precision: 1.49% | Recall: 21.09% | Expected Conversions: 7.47
K=1000 | Precision: 1.14% | Recall: 34.56% | Expected Conversions: 11.40
K=1500 | Precision: 0.94% | Recall: 42.25% | Expected Conversions: 14.07
K=2000 | Precision: 0.78% | Recall: 46.89% | Expected Conversions: 15.53
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='altpay1_turnover' ASC
K=500  | Precision: 0.81% | Recall: 10.79% | Expected Conversions: 4.07
K=1000 | Precision: 0.79% | Recall: 21.75% | Expected Conversions: 7.93
K=1500 | Precision: 0.76% | Recall: 31.58% | Expected Conversions: 11.40
K=2000 | Precision: 0.73% | Recall: 40.64% | Expected Conversions: 14.60
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='altpay2_turnover' ASC
K=500  | Precision: 0.69% | Recall: 9.22% | Expected Conversions: 3.47
K=1000 | Precision: 0.60% | Recall: 18.29% | Expected Conversions: 6.00
K=1500 | Precision: 0.62% | Recall: 27.53% | Expected Conversions: 9.33
K=2000 | Precision: 0.61% | Recall: 35.99% | Expected Conversions: 12.27
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='altpay3_turnover' ASC
K=500  | Precision: 0.48% | Recall: 6.10% | Expected Conversions: 2.40
K=1000 | Precision: 0.46% | Recall: 13.44% | Expected Conversions: 4.60
K=1500 | Precision: 0.51% | Recall: 22.41% | Expected Conversions: 7.60
K=2000 | Precision: 0.63% | Recall: 36.76% | Expected Conversions: 12.67
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='altpay4_turnover' ASC
K=500  | Precision: 0.76% | Recall: 9.93% | Expected Conversions: 3.80
K=1000 | Precision: 0.66% | Recall: 20.16% | Expected Conversions: 6.60
K=1500 | Precision: 0.65% | Recall: 28.90% | Expected Conversions: 9.73
K=2000 | Precision: 0.66% | Recall: 39.47% | Expected Conversions: 13.20
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='altpay5_turnover' ASC
K=500  | Precision: 0.79% | Recall: 10.34% | Expected Conversions: 3.93
K=1000 | Precision: 0.73% | Recall: 22.06% | Expected Conversions: 7.33
K=1500 | Precision: 0.74% | Recall: 32.07% | Expected Conversions: 11.07
K=2000 | Precision: 0.73% | Recall: 42.84% | Expected Conversions: 14.53
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='altpay6_turnover' ASC
K=500  | Precision: 0.71% | Recall: 9.03% | Expected Conversions: 3.53
K=1000 | Precision: 0.67% | Recall: 20.12% | Expected Conversions: 6.73
K=1500 | Precision: 0.67% | Recall: 29.02% | Expected Conversions: 10.00
K=2000 | Precision: 0.67% | Recall: 39.63% | Expected Conversions: 13.47
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx' ASC
K=500  | Precision: 0.71% | Recall: 11.00% | Expected Conversions: 3.53
K=1000 | Precision: 0.79% | Recall: 22.60% | Expected Conversions: 7.87
K=1500 | Precision: 0.76% | Recall: 32.65% | Expected Conversions: 11.47
K=2000 | Precision: 0.76% | Recall: 44.84% | Expected Conversions: 15.20
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover' ASC
K=500  | Precision: 0.65% | Recall: 9.28% | Expected Conversions: 3.27
K=1000 | Precision: 0.65% | Recall: 17.70% | Expected Conversions: 6.47
K=1500 | Precision: 0.65% | Recall: 27.58% | Expected Conversions: 9.80
K=2000 | Precision: 0.73% | Recall: 41.98% | Expected Conversions: 14.60
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='other_active_product_cnt' ASC
K=500  | Precision: 0.57% | Recall: 7.62% | Expected Conversions: 2.87
K=1000 | Precision: 0.58% | Recall: 17.05% | Expected Conversions: 5.80
K=1500 | Precision: 0.56% | Recall: 25.63% | Expected Conversions: 8.40
K=2000 | Precision: 0.58% | Recall: 35.42% | Expected Conversions: 11.60
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='active_mcc_cnt' ASC
K=500  | Precision: 0.75% | Recall: 9.99% | Expected Conversions: 3.73
K=1000 | Precision: 0.67% | Recall: 19.53% | Expected Conversions: 6.67
K=1500 | Precision: 0.68% | Recall: 30.32% | Expected Conversions: 10.20
K=2000 | Precision: 0.70% | Recall: 42.14% | Expected Conversions: 13.93
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='active_gateway_cnt' ASC
K=500  | Precision: 0.25% | Recall: 2.94% | Expected Conversions: 1.27
K=1000 | Precision: 0.33% | Recall: 10.46% | Expected Conversions: 3.33
K=1500 | Precision: 0.38% | Recall: 17.73% | Expected Conversions: 5.67
K=2000 | Precision: 0.54% | Recall: 33.30% | Expected Conversions: 10.87
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='avg_check' ASC
K=500  | Precision: 0.49% | Recall: 6.13% | Expected Conversions: 2.47
K=1000 | Precision: 0.63% | Recall: 18.09% | Expected Conversions: 6.27
K=1500 | Precision: 0.66% | Recall: 29.08% | Expected Conversions: 9.87
K=2000 | Precision: 0.74% | Recall: 43.77% | Expected Conversions: 14.73
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_ma_2m' ASC
K=500  | Precision: 0.73% | Recall: 10.42% | Expected Conversions: 3.67
K=1000 | Precision: 0.64% | Recall: 17.40% | Expected Conversions: 6.40
K=1500 | Precision: 0.65% | Recall: 27.75% | Expected Conversions: 9.80
K=2000 | Precision: 0.74% | Recall: 42.77% | Expected Conversions: 14.80
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_ema_2m' ASC
K=500  | Precision: 0.72% | Recall: 9.93% | Expected Conversions: 3.60
K=1000 | Precision: 0.65% | Recall: 18.18% | Expected Conversions: 6.53
K=1500 | Precision: 0.63% | Recall: 26.55% | Expected Conversions: 9.40
K=2000 | Precision: 0.74% | Recall: 42.48% | Expected Conversions: 14.73
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_ma_3m' ASC
K=500  | Precision: 0.80% | Recall: 11.44% | Expected Conversions: 4.00
K=1000 | Precision: 0.63% | Recall: 17.46% | Expected Conversions: 6.33
K=1500 | Precision: 0.63% | Recall: 26.73% | Expected Conversions: 9.40
K=2000 | Precision: 0.73% | Recall: 42.00% | Expected Conversions: 14.53
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_ema_3m' ASC
K=500  | Precision: 0.77% | Recall: 10.92% | Expected Conversions: 3.87
K=1000 | Precision: 0.64% | Recall: 17.66% | Expected Conversions: 6.40
K=1500 | Precision: 0.64% | Recall: 27.47% | Expected Conversions: 9.60
K=2000 | Precision: 0.73% | Recall: 41.29% | Expected Conversions: 14.60
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_ma_6m' ASC
K=500  | Precision: 0.85% | Recall: 11.82% | Expected Conversions: 4.27
K=1000 | Precision: 0.66% | Recall: 18.17% | Expected Conversions: 6.60
K=1500 | Precision: 0.66% | Recall: 28.53% | Expected Conversions: 9.93
K=2000 | Precision: 0.73% | Recall: 41.85% | Expected Conversions: 14.67
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_ema_6m' ASC
K=500  | Precision: 0.77% | Recall: 10.88% | Expected Conversions: 3.87
K=1000 | Precision: 0.63% | Recall: 17.14% | Expected Conversions: 6.27
K=1500 | Precision: 0.66% | Recall: 28.17% | Expected Conversions: 9.87
K=2000 | Precision: 0.73% | Recall: 42.27% | Expected Conversions: 14.60
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_ma_2m' ASC
K=500  | Precision: 0.76% | Recall: 11.83% | Expected Conversions: 3.80
K=1000 | Precision: 0.81% | Recall: 23.26% | Expected Conversions: 8.07
K=1500 | Precision: 0.77% | Recall: 34.01% | Expected Conversions: 11.60
K=2000 | Precision: 0.77% | Recall: 45.29% | Expected Conversions: 15.33
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_ema_2m' ASC
K=500  | Precision: 0.76% | Recall: 11.86% | Expected Conversions: 3.80
K=1000 | Precision: 0.75% | Recall: 21.75% | Expected Conversions: 7.53
K=1500 | Precision: 0.76% | Recall: 33.66% | Expected Conversions: 11.47
K=2000 | Precision: 0.77% | Recall: 45.40% | Expected Conversions: 15.40
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_ma_3m' ASC
K=500  | Precision: 0.80% | Recall: 12.46% | Expected Conversions: 4.00
K=1000 | Precision: 0.81% | Recall: 23.58% | Expected Conversions: 8.07
K=1500 | Precision: 0.77% | Recall: 32.75% | Expected Conversions: 11.53
K=2000 | Precision: 0.77% | Recall: 45.40% | Expected Conversions: 15.40
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_ema_3m' ASC
K=500  | Precision: 0.75% | Recall: 11.63% | Expected Conversions: 3.73
K=1000 | Precision: 0.78% | Recall: 22.50% | Expected Conversions: 7.80
K=1500 | Precision: 0.76% | Recall: 32.67% | Expected Conversions: 11.47
K=2000 | Precision: 0.77% | Recall: 45.51% | Expected Conversions: 15.47
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_ma_6m' ASC
K=500  | Precision: 0.81% | Recall: 12.42% | Expected Conversions: 4.07
K=1000 | Precision: 0.77% | Recall: 22.71% | Expected Conversions: 7.73
K=1500 | Precision: 0.78% | Recall: 33.24% | Expected Conversions: 11.67
K=2000 | Precision: 0.77% | Recall: 45.40% | Expected Conversions: 15.40
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_ema_6m' ASC
K=500  | Precision: 0.80% | Recall: 12.41% | Expected Conversions: 4.00
K=1000 | Precision: 0.80% | Recall: 23.61% | Expected Conversions: 8.00
K=1500 | Precision: 0.78% | Recall: 34.30% | Expected Conversions: 11.73
K=2000 | Precision: 0.77% | Recall: 45.29% | Expected Conversions: 15.33
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='avg_check_wma_2m' ASC
K=500  | Precision: 0.49% | Recall: 6.05% | Expected Conversions: 2.47
K=1000 | Precision: 0.64% | Recall: 17.83% | Expected Conversions: 6.40
K=1500 | Precision: 0.66% | Recall: 28.94% | Expected Conversions: 9.87
K=2000 | Precision: 0.73% | Recall: 43.57% | Expected Conversions: 14.67
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='avg_check_wma_3m' ASC
K=500  | Precision: 0.51% | Recall: 6.35% | Expected Conversions: 2.53
K=1000 | Precision: 0.65% | Recall: 18.13% | Expected Conversions: 6.53
K=1500 | Precision: 0.65% | Recall: 28.83% | Expected Conversions: 9.80
K=2000 | Precision: 0.72% | Recall: 42.71% | Expected Conversions: 14.40
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='avg_check_wma_6m' ASC
K=500  | Precision: 0.49% | Recall: 6.23% | Expected Conversions: 2.47
K=1000 | Precision: 0.65% | Recall: 18.28% | Expected Conversions: 6.53
K=1500 | Precision: 0.65% | Recall: 28.46% | Expected Conversions: 9.73
K=2000 | Precision: 0.72% | Recall: 42.75% | Expected Conversions: 14.47
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_cv_2m' ASC
K=500  | Precision: 1.01% | Recall: 13.60% | Expected Conversions: 5.07
K=1000 | Precision: 0.79% | Recall: 23.78% | Expected Conversions: 7.87
K=1500 | Precision: 0.70% | Recall: 31.46% | Expected Conversions: 10.47
K=2000 | Precision: 0.66% | Recall: 39.48% | Expected Conversions: 13.13
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_cv_3m' ASC
K=500  | Precision: 1.03% | Recall: 14.94% | Expected Conversions: 5.13
K=1000 | Precision: 0.73% | Recall: 21.54% | Expected Conversions: 7.27
K=1500 | Precision: 0.66% | Recall: 30.01% | Expected Conversions: 9.93
K=2000 | Precision: 0.63% | Recall: 38.38% | Expected Conversions: 12.67
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_cv_6m' ASC
K=500  | Precision: 1.01% | Recall: 14.85% | Expected Conversions: 5.07
K=1000 | Precision: 0.70% | Recall: 21.49% | Expected Conversions: 7.00
K=1500 | Precision: 0.65% | Recall: 30.13% | Expected Conversions: 9.80
K=2000 | Precision: 0.64% | Recall: 38.13% | Expected Conversions: 12.87
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_change_to_prev_month' ASC
K=500  | Precision: 0.55% | Recall: 7.09% | Expected Conversions: 2.73
K=1000 | Precision: 0.55% | Recall: 14.27% | Expected Conversions: 5.47
K=1500 | Precision: 0.69% | Recall: 29.15% | Expected Conversions: 10.33
K=2000 | Precision: 0.66% | Recall: 38.88% | Expected Conversions: 13.27
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_change_to_prev_month' ASC
K=500  | Precision: 0.45% | Recall: 5.82% | Expected Conversions: 2.27
K=1000 | Precision: 0.52% | Recall: 13.47% | Expected Conversions: 5.20
K=1500 | Precision: 0.64% | Recall: 27.38% | Expected Conversions: 9.67
K=2000 | Precision: 0.66% | Recall: 38.61% | Expected Conversions: 13.13
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='avg_check_change_to_prev_month' ASC
K=500  | Precision: 0.68% | Recall: 9.24% | Expected Conversions: 3.40
K=1000 | Precision: 0.65% | Recall: 17.98% | Expected Conversions: 6.53
K=1500 | Precision: 0.80% | Recall: 35.12% | Expected Conversions: 11.93
K=2000 | Precision: 0.69% | Recall: 40.61% | Expected Conversions: 13.80
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_change_to_turnover_ma_2m' ASC
K=500  | Precision: 0.55% | Recall: 7.09% | Expected Conversions: 2.73
K=1000 | Precision: 0.55% | Recall: 14.27% | Expected Conversions: 5.47
K=1500 | Precision: 0.69% | Recall: 29.15% | Expected Conversions: 10.33
K=2000 | Precision: 0.66% | Recall: 38.60% | Expected Conversions: 13.13
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_change_to_turnover_ma_3m' ASC
K=500  | Precision: 0.55% | Recall: 7.11% | Expected Conversions: 2.73
K=1000 | Precision: 0.55% | Recall: 14.56% | Expected Conversions: 5.47
K=1500 | Precision: 0.64% | Recall: 27.44% | Expected Conversions: 9.60
K=2000 | Precision: 0.64% | Recall: 36.71% | Expected Conversions: 12.73
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_change_to_turnover_ma_6m' ASC
K=500  | Precision: 0.53% | Recall: 6.89% | Expected Conversions: 2.67
K=1000 | Precision: 0.59% | Recall: 16.44% | Expected Conversions: 5.87
K=1500 | Precision: 0.64% | Recall: 27.52% | Expected Conversions: 9.60
K=2000 | Precision: 0.65% | Recall: 38.69% | Expected Conversions: 13.07
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_change_to_turnover_ema_2m' ASC
K=500  | Precision: 0.51% | Recall: 6.59% | Expected Conversions: 2.53
K=1000 | Precision: 0.54% | Recall: 14.40% | Expected Conversions: 5.40
K=1500 | Precision: 0.66% | Recall: 27.87% | Expected Conversions: 9.87
K=2000 | Precision: 0.65% | Recall: 37.56% | Expected Conversions: 13.00
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_change_to_turnover_ema_3m' ASC
K=500  | Precision: 0.49% | Recall: 6.29% | Expected Conversions: 2.47
K=1000 | Precision: 0.54% | Recall: 14.81% | Expected Conversions: 5.40
K=1500 | Precision: 0.66% | Recall: 27.39% | Expected Conversions: 9.87
K=2000 | Precision: 0.65% | Recall: 37.12% | Expected Conversions: 12.93
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='turnover_change_to_turnover_ema_6m' ASC
K=500  | Precision: 0.48% | Recall: 6.12% | Expected Conversions: 2.40
K=1000 | Precision: 0.58% | Recall: 16.16% | Expected Conversions: 5.80
K=1500 | Precision: 0.65% | Recall: 27.96% | Expected Conversions: 9.80
K=2000 | Precision: 0.64% | Recall: 37.62% | Expected Conversions: 12.80
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_change_to_cnt_trx_ma_2m' ASC
K=500  | Precision: 0.45% | Recall: 5.82% | Expected Conversions: 2.27
K=1000 | Precision: 0.52% | Recall: 13.47% | Expected Conversions: 5.20
K=1500 | Precision: 0.64% | Recall: 27.38% | Expected Conversions: 9.67
K=2000 | Precision: 0.66% | Recall: 38.75% | Expected Conversions: 13.20
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_change_to_cnt_trx_ma_3m' ASC
K=500  | Precision: 0.52% | Recall: 6.65% | Expected Conversions: 2.60
K=1000 | Precision: 0.57% | Recall: 14.76% | Expected Conversions: 5.73
K=1500 | Precision: 0.62% | Recall: 25.62% | Expected Conversions: 9.33
K=2000 | Precision: 0.65% | Recall: 38.87% | Expected Conversions: 12.93
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_change_to_cnt_trx_ma_6m' ASC
K=500  | Precision: 0.60% | Recall: 9.51% | Expected Conversions: 3.00
K=1000 | Precision: 0.60% | Recall: 18.02% | Expected Conversions: 6.00
K=1500 | Precision: 0.64% | Recall: 27.21% | Expected Conversions: 9.53
K=2000 | Precision: 0.66% | Recall: 39.71% | Expected Conversions: 13.13
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_change_to_cnt_trx_ema_2m' ASC
K=500  | Precision: 0.51% | Recall: 7.29% | Expected Conversions: 2.53
K=1000 | Precision: 0.52% | Recall: 14.53% | Expected Conversions: 5.20
K=1500 | Precision: 0.63% | Recall: 25.82% | Expected Conversions: 9.40
K=2000 | Precision: 0.65% | Recall: 37.21% | Expected Conversions: 12.93
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_change_to_cnt_trx_ema_3m' ASC
K=500  | Precision: 0.52% | Recall: 6.61% | Expected Conversions: 2.60
K=1000 | Precision: 0.51% | Recall: 13.58% | Expected Conversions: 5.13
K=1500 | Precision: 0.65% | Recall: 29.31% | Expected Conversions: 9.80
K=2000 | Precision: 0.65% | Recall: 39.42% | Expected Conversions: 13.07
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='cnt_trx_change_to_cnt_trx_ema_6m' ASC
K=500  | Precision: 0.57% | Recall: 8.15% | Expected Conversions: 2.87
K=1000 | Precision: 0.58% | Recall: 16.52% | Expected Conversions: 5.80
K=1500 | Precision: 0.63% | Recall: 26.81% | Expected Conversions: 9.47
K=2000 | Precision: 0.65% | Recall: 37.64% | Expected Conversions: 13.00
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='avg_check_change_to_avg_check_wma_2m' ASC
K=500  | Precision: 0.65% | Recall: 8.75% | Expected Conversions: 3.27
K=1000 | Precision: 0.65% | Recall: 17.97% | Expected Conversions: 6.53
K=1500 | Precision: 0.85% | Recall: 38.64% | Expected Conversions: 12.80
K=2000 | Precision: 0.76% | Recall: 45.82% | Expected Conversions: 15.27
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='avg_check_change_to_avg_check_wma_3m' ASC
K=500  | Precision: 0.63% | Recall: 8.28% | Expected Conversions: 3.13
K=1000 | Precision: 0.63% | Recall: 18.91% | Expected Conversions: 6.33
K=1500 | Precision: 0.84% | Recall: 36.38% | Expected Conversions: 12.53
K=2000 | Precision: 0.75% | Recall: 43.20% | Expected Conversions: 15.00
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='avg_check_change_to_avg_check_wma_6m' ASC
K=500  | Precision: 0.57% | Recall: 7.32% | Expected Conversions: 2.87
K=1000 | Precision: 0.65% | Recall: 17.65% | Expected Conversions: 6.53
K=1500 | Precision: 0.82% | Recall: 35.45% | Expected Conversions: 12.27
K=2000 | Precision: 0.74% | Recall: 43.76% | Expected Conversions: 14.87
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29

y_score='lifetime_month_streak_inn' DESC
K=500  | Precision: 0.45% | Recall: 6.17% | Expected Conversions: 2.27
K=1000 | Precision: 0.40% | Recall: 11.27% | Expected Conversions: 4.00
K=1500 | Precision: 0.46% | Recall: 20.61% | Expected Conversions: 6.93
K=2000 | Precision: 0.55% | Recall: 33.39% | Expected Conversions: 11.00
K=2500 | Precision: 0.74% | Recall: 51.25% | Expected Conversions: 17.29
